package main

import (
	// "fmt"
	"net/http"
	"log"
	"sync/atomic"
	"database/sql"
	"os"
	"github.com/joho/godotenv"
	_ "github.com/lib/pq"
	"github.com/eboot-dev/chirpy/internal/database"
)

/* Utils */

/* Handlers */

/* Middlewares */

// This is a looging middleware. It logs the Method and URL.Path of a request and pass it to the next handler to be processed
func middlewareLogger(nextHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		log.Printf("%s %s", req.Method, req.URL.Path)
		nextHandler.ServeHTTP(w, req)
	})
}

type apiConfig struct {
		fileserverHits 	atomic.Int32 		// counts how many times a request is made
		db 				*database.Queries   // store the db queries generated by sqlc
		platform 		string				// store the environment we are running 
}

func main() {
	const port = "8080"

	const rootRoutePath = "/app/"
	const rootRoutePrefix = "/app"
	const rootFilePath = "."
	
	const assetsRoutePath = "/assets"
	const assetsFilePath = "/assets"

	const readinessRoutePath = "GET /api/healthz"
	const metricsRoutePath = "GET /admin/metrics"
	const metricsResetRoutePath = "POST /admin/reset"

	const chirpRoutePath = "POST /api/chirps"
	
	const usersRoutePath = "POST /api/users"	
	
	// Load the `.env` file
	godotenv.Load()
	dbURL := os.Getenv("DB_URL")
	if dbURL == "" {
		log.Fatal("ERROR: DB_URL env variable must be set")
	}
	platform := os.Getenv("PLATFORM")
	if dbURL == "" {
		log.Fatal("ERROR: PLATFORM env variable must be set")
	}

	// Connect to db
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatalf("ERROR: Can't establish connection with DB %s",err)
	}
	dbQueries := database.New(db)

	// init apiConfig struct
	apiCfg := apiConfig{
		fileserverHits: atomic.Int32{},
		db: 			dbQueries,
		platform: 		platform,
	}

	log.Println("Starting up server...")
	mux := http.NewServeMux()
	/* Registering Handlers */
	
	// FileServer handler
	fsHandler := http.FileServer(http.Dir(rootFilePath))
	fsHandler = apiCfg.middlewareMetricsInc(fsHandler)
	fsHandler = http.StripPrefix(rootRoutePrefix,fsHandler)
	mux.Handle(rootRoutePath,middlewareLogger(fsHandler))
	
	// FileServer: assets
	assetsHandler := http.FileServer(http.Dir(rootFilePath + assetsFilePath))
	mux.Handle(assetsRoutePath,assetsHandler)

	// API Readiness Endpoint (healthz)
	mux.HandleFunc(readinessRoutePath,readinessHandler)
	
	// API Users Endpoint
	mux.HandleFunc(usersRoutePath,apiCfg.usersCreateHandler)
	// API Chirps Endpoint
	mux.HandleFunc(chirpRoutePath,apiCfg.chirpsCreateHandler)
	
	// ADMIN Metrics Endpoint
	mux.HandleFunc(metricsRoutePath,apiCfg.metricsHandler)
	// ADMIN Metrics Reset Endpoint
	mux.HandleFunc(metricsResetRoutePath,apiCfg.metricsResetHandler)	

	server := &http.Server{
		Handler: mux,
		Addr: ":" +port,
	}

	log.Printf("Listening and Serving on port: %s", port)
	log.Fatal(server.ListenAndServe())
}
