package main

import (
	"net/http"
	"sync/atomic"
	"fmt"
	"log"
	"github.com/eboot-dev/chirpy/internal/database"
)

type apiConfig struct {
		fileserverHits atomic.Int32 // counts how many times a request is made
		db *database.Queries    // store the db queries generated by sqlc
		env string			// store the environment we are running 
	}

// Metrics endpoint handler. It shows the number of requests made to the server.
func (c *apiConfig) metricsHandler(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Content-Type","text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(fmt.Sprintf(`
<html>
	<body>
		<h1>Welcome, Chirpy Admin</h1>
		<p>Chirpy has been visited %d times!</p>
	</body>
</html>`, c.fileserverHits.Load())))
}

// Reset Metrics endpoint handler. It resets the counter of number of requests made to the server.
func (c *apiConfig) metricsResetHandler(w http.ResponseWriter, req *http.Request) {
	if c.env != "dev" {
		log.Println("ERROR: Accessing reset endpoint in a not `dev` environment")
		w.WriteHeader(http.StatusForbidden)
		return
	}
	log.Printf("Resetting fileserverHits... (last value %d)",c.fileserverHits.Load())
	log.Println("Delete all users")
	err := c.db.DeleteUsers(req.Context())
	if err != nil {
		log.Println("ERROR: Can't Delete all users %s",err)
	}
	c.fileserverHits.Store(0)
	w.WriteHeader(http.StatusOK)
	// This might be inefficient, see: https://stackoverflow.com/questions/37863374/whats-the-difference-between-responsewriter-write-and-io-writestring
	w.Write([]byte("Hits reset to 0"))
}

// This is a metric middleware. It keeps tracks of the number of requests received
func (c *apiConfig) middlewareMetricsInc(nextHandler http.Handler) http.Handler {
	return http.HandlerFunc( func(w http.ResponseWriter, req *http.Request) {
		// log.Printf("Old hits: %d",c.fileserverHits.Load())
		c.fileserverHits.Add(1)
		nextHandler.ServeHTTP(w,req)
	})
}

